platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

targetArray = ['DSSky', 'DSSkyUITests', 'DSSkyTests']

targetArray.each do |t|
  target t do
    
    pod 'Moya'
    pod 'SwiftyJSON'
    pod 'SnapKit'
    pod 'MBProgressHUD'
    pod 'AMapLocation-NO-IDFA'
    pod 'AMapSearch-NO-IDFA'
    pod 'SwiftyUserDefaults', '4.0.0-beta.1'
    
  end
end
