# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DSSky' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DSSky
    pod 'Moya'
    pod 'SwiftyJSON'
    pod 'SnapKit'
    pod 'MBProgressHUD'
    pod 'AMapLocation-NO-IDFA'

  target 'DSSkyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DSSkyUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Moya'
    pod 'SwiftyJSON'
    pod 'SnapKit'
    pod 'MBProgressHUD'
    
  end

end
